### ISSUE TITLE
Add config option for 'minimum interval between checks'

### ISSUE THREAD

**Issue by kdave** [buckket/twtxt#100]
During experimenting, the 'timeline' option can be run quite often though there are no changes. The cache works, but still has to ping the remote servers for no reason.

I'd like to see a config option that would let the 'timeline' command use just the cache and skip connecting to the remotes if this happens within the configured period. For parity, there would need to be a commandline option to override the behaviour.
The default could be a few seconds or a minute, whatever.

**Comment by LeMagnesium** [comment]
Here's an attempt I made. It could be useful.
I first encountered some issues due to the way cache objects are created but quickly understood how to work around them. The expected results are provided : https://github.com/LeMagnesium/twtxt/commit/6bbe8a7838d3480a564cbfe2400fcaa249964a4c
(I used 10 seconds as default value for `timeline_update_interval`)

**Comment by timofurrer** [comment]
Why don't you submit a PR?
