### ISSUE TITLE
Sort timeline in ascending or descending order

### ISSUE THREAD

**Issue by buckket** [buckket/twtxt#5]
Implement a config option to switch between an ascending or descending timeline.

**Comment by welandtb** [comment]
So I'm, uh, kind of playing with this, and "ascending" and "descending" always confuse the hell out of me. Am I getting this straight?

Ascending = posts are output starting with the _oldest_ (i.e. smallest epoch time), so that the _last_ post that is printed to stdout is the most recent one (i.e. with the largest epoch time)

Descending = posts are output starting with the _newest_ (i.e. largest epoch time), so that the _last_ post that is printed to stdout is the oldest one (i.e. with the smallest epoch time)

**Comment by buckket** [comment]
@welandtb Correct! :+1:

**Comment by welandtb** [comment]
Awesome! Now, let's see how different Python 3 and 2 really are :-).
